# Generated by Django 5.2.6 on 2025-10-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='uploads/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=128, null=True)),
                ('program_title', models.TextField(blank=True, null=True)),
                ('proposed_effective_date', models.DateField(blank=True, null=True)),
                ('approved_effective_date', models.DateField(blank=True, null=True)),
                ('amended_effective_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], help_text='U.S. state (2-letter code)', max_length=2, null=True)),
                ('application_type', models.CharField(choices=[('RENEWAL', 'Renewal'), ('AMENDMENT', 'Amendment'), ('NEW', 'New')], default='POLICY', help_text='Is this a policy or an amendment?', max_length=32)),
                ('extra', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='chunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.waiverdocument'),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.waiverdocument'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.waiverdocument'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
