# Generated by Django 5.2.6 on 2025-10-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_waiverdocument_alter_chunk_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiverdocument',
            name='group',
        ),
        migrations.AddField(
            model_name='waiverdocument',
            name='application_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
